-- Add durable identities and user-owned API keys without changing any legacy
-- library IDs. The existing library becomes the bootstrap user's personal
-- library after the application validates that mapping at startup.

alter table library
    add column kind text not null default 'personal',
    add constraint library_id_positive check (id > 0),
    add constraint library_kind_valid check (kind in ('personal', 'group'));
alter table library alter column kind drop default;
alter table library alter column id add generated by default as identity;
select setval(
    pg_get_serial_sequence('library', 'id'),
    coalesce(max(id), 1),
    max(id) is not null
)
from library;
alter table library
    add constraint library_id_kind_key unique (id, kind);

create table users (
    id           bigint generated by default as identity primary key,
    username     text        not null unique,
    display_name text        not null,
    disabled_at  timestamptz,
    created_at   timestamptz not null default now(),
    constraint users_id_positive check (id > 0),
    constraint users_username_nonempty check (btrim(username) <> ''),
    constraint users_display_name_nonempty check (btrim(display_name) <> '')
);

create table external_identities (
    issuer     text        not null,
    subject    text        not null,
    user_id    bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (issuer, subject),
    constraint external_identities_issuer_nonempty check (btrim(issuer) <> ''),
    constraint external_identities_subject_nonempty check (btrim(subject) <> '')
);
create index external_identities_user_id_idx on external_identities (user_id);

create table personal_libraries (
    user_id      bigint primary key references users (id) on delete restrict,
    library_id   bigint not null unique,
    library_kind text   not null default 'personal',
    constraint personal_libraries_kind check (library_kind = 'personal'),
    constraint personal_libraries_library_fk
        foreign key (library_id, library_kind)
        references library (id, kind) on delete restrict
);

create table api_keys (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    name       text        not null,
    token_hash bytea       not null unique,
    created_at timestamptz not null default now(),
    revoked_at timestamptz,
    constraint api_keys_id_positive check (id > 0),
    constraint api_keys_name_nonempty check (btrim(name) <> ''),
    constraint api_keys_sha256_length check (octet_length(token_hash) = 32)
);
create index api_keys_user_id_idx on api_keys (user_id);

create table api_key_user_permissions (
    api_key_id bigint primary key references api_keys (id) on delete cascade,
    library    boolean not null default false,
    notes      boolean not null default false,
    write      boolean not null default false,
    files      boolean not null default false,
    constraint api_key_user_permissions_require_library
        check (library or not (notes or write or files))
);
