-- Private group discovery and API-key grants. Group metadata has its own
-- version because desktop clients discover changed libraries before syncing
-- each group's independently versioned library.

create table groups (
    id              bigint generated by default as identity primary key,
    library_id      bigint      not null unique,
    library_kind    text        not null default 'group',
    owner_user_id   bigint      not null references users (id) on delete restrict,
    owner_role      text        generated always as ('owner') stored,
    name            text        not null,
    description     text        not null default '',
    url             text        not null default '',
    type            text        not null default 'Private',
    library_reading text        not null default 'members',
    library_editing text        not null default 'members',
    file_editing    text        not null default 'members',
    version         bigint      not null default 1,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint groups_id_positive check (id > 0),
    constraint groups_name_nonempty check (btrim(name) <> ''),
    constraint groups_private_type check (type = 'Private'),
    constraint groups_library_kind check (library_kind = 'group'),
    constraint groups_owner_role check (owner_role = 'owner'),
    constraint groups_library_reading_valid
        check (library_reading in ('members', 'all')),
    constraint groups_library_editing_valid
        check (library_editing in ('admins', 'members')),
    constraint groups_file_editing_valid
        check (file_editing in ('none', 'admins', 'members')),
    constraint groups_version_positive check (version > 0),
    constraint groups_library_fk
        foreign key (library_id, library_kind)
        references library (id, kind) on delete restrict
);

create table group_memberships (
    group_id  bigint      not null references groups (id) on delete cascade,
    user_id   bigint      not null references users (id) on delete cascade,
    role      text        not null,
    created_at timestamptz not null default now(),
    primary key (group_id, user_id),
    constraint group_memberships_group_user_role_key
        unique (group_id, user_id, role),
    constraint group_memberships_role_valid
        check (role in ('owner', 'admin', 'member'))
);
create unique index group_memberships_one_owner_idx
    on group_memberships (group_id) where role = 'owner';
create index group_memberships_user_id_idx
    on group_memberships (user_id, group_id);

alter table groups
    add constraint groups_owner_membership_fk
    foreign key (id, owner_user_id, owner_role)
    references group_memberships (group_id, user_id, role)
    deferrable initially deferred;

create table api_key_all_groups_permissions (
    api_key_id bigint primary key references api_keys (id) on delete cascade,
    library    boolean not null default false,
    write      boolean not null default false,
    constraint api_key_all_groups_permissions_write_requires_library
        check (library or not write)
);

create table api_key_group_permissions (
    api_key_id bigint  not null,
    user_id    bigint  not null,
    group_id   bigint  not null,
    library    boolean not null default false,
    write      boolean not null default false,
    primary key (api_key_id, group_id),
    constraint api_key_group_permissions_key_owner_fk
        foreign key (api_key_id, user_id)
        references api_keys (id, user_id) on delete cascade,
    constraint api_key_group_permissions_membership_fk
        foreign key (group_id, user_id)
        references group_memberships (group_id, user_id) on delete cascade,
    constraint api_key_group_permissions_write_requires_library
        check (library or not write)
);
