name: Auto Merge Dependency Updates
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
jobs:
  auto-merge-dependency-updates:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: "auto-merge:${{ github.head_ref }}"
      cancel-in-progress: true
    steps:
      - name: Auto Merge
        uses: Mic92/auto-merge@main
        with:
          repo-token: ${{ github.token }}
          approve: false
          merge-method: merge
